drop table z_CUSTOMER_PURCHASE
drop table z_CUSTOMER;
drop function FN_GET_CUSTOMER_NAME;


--CUSTOMER(고객) 테이블 생성
CREATE TABLE z_CUSTOMER(
	 ID INT IDENTITY(1,1) PRIMARY KEY--아이디
	,NAME NVARCHAR(30)--이름
)
--CUSTOMER_PURCHASE(고객 구매 리스트) 테이블 생성
CREATE TABLE z_CUSTOMER_PURCHASE(
	 PURCHASE_NO INT IDENTITY(1,1) PRIMARY KEY--구매번호
	,ID INT FOREIGN KEY REFERENCES z_CUSTOMER(ID)--아이디
	,ITEM NVARCHAR(30)--품목
	,QTY INT--수량
	,PRICE INT--가격
)
--ID입력시 [NAME]을 반환해주는 FN_GET_CUSTOMER_NAME 함수 생성
CREATE FUNCTION FN_GET_CUSTOMER_NAME(@ID INT)
RETURNS TABLE
AS
RETURN
(
	SELECT [NAME] FROM z_CUSTOMER(NOLOCK) WHERE ID = @ID
)

--데이터 생성
INSERT z_CUSTOMER VALUES ('ALICE')
INSERT z_CUSTOMER VALUES ('BOB')
INSERT z_CUSTOMER VALUES ('SAM')

INSERT z_CUSTOMER_PURCHASE VALUES (1,'ITEM1',1,1000)
INSERT z_CUSTOMER_PURCHASE VALUES (1,'ITEM2',1,2000)
INSERT z_CUSTOMER_PURCHASE VALUES (1,'ITEM3',1,3000)
INSERT z_CUSTOMER_PURCHASE VALUES (2,'ITEM1',2,2000)
INSERT z_CUSTOMER_PURCHASE VALUES (2,'ITEM2',3,6000)
INSERT z_CUSTOMER_PURCHASE VALUES (2,'ITEM4',1,4000)
INSERT z_CUSTOMER_PURCHASE VALUES (2,'ITEM5',1,5000)

--고객 정보 확인
SELECT * FROM z_CUSTOMER
--고객 구매 리스트 정보 확인 
SELECT * FROM z_CUSTOMER_PURCHASE


--CROSS APPLY를 이용하여 CUSTOMER와 조인 후 NAME 표시
SELECT A.PURCHASE_NO, A.ID, B.[NAME], A.ITEM, A.QTY, A.PRICE
FROM z_CUSTOMER_PURCHASE A
CROSS APPLY (SELECT * FROM z_CUSTOMER B WHERE A.ID = B.ID) B


--동일한 결과 반환하는 INNER JOIN
--SELECT A.PURCHASE_NO, A.ID, B.[NAME], A.ITEM, A.QTY, A.PRICE
--FROM CUSTOMER_PURCHASE A
--INNER JOIN CUSTOMER B ON A.ID = B.ID

